### ISSUE TITLE
CMake build error

### ISSUE THREAD

**Issue by scottfurry** [SRombauts/SQLiteCpp_Example#2]
Following steps from README, CMake reports the following:</br>
`
 CMake Error at CMakeLists.txt:23 (else):
 A duplicate ELSE command was found inside an IF block.
 -- Configuring incomplete, errors occurred!
`
Changing line CMakeLists.txt:line 20 from:</br>
`else(UNIX AND APPLE)`</br>
to</br>
`elseif(UNIX AND APPLE)`</br>

resolves the error and is, I think, the intention of the code.

**Comment by ccf19881030** [comment]
when I following steps from the README to build the SQLiteCpp_Example project on CentOS7.6 Operating System, get the same error:
```cpp
CMake Error at CMakeLists.txt:23 (else):
  A duplicate ELSE command was found inside an IF block.


-- Configuring incomplete, errors occurred!

```
Thanks to scottfurry.

**Comment by bigOconstant** [comment]
I also got this error in ubuntu 18.04 WSL. Deleting the else blocks for windows and apple got me through the error.

**Comment by SRombauts** [comment]
Sorry for the confusion, this was somehow "working" with older CMake versions but I fixed it today.

Thanks also for the two of you submitting a pull request fix it, I appreciate it!

**Comment by scottfurry** [comment]
One of the difficulties with Open Source, and the bane of "agile" methods, revisions keep changing. Not always easy to hit a constantly moving target. Good we got this squared away.
